Fix `create_sponsors_table` migration [WEB-133]
Unfortunately, this caused errors during phpunit:

  PDOException: SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL
  column with default value NULL

I fixed it previously in `make_sponsor_id_nullable_on_events`, but that
wasn't enough, so fixing it at the source.